# Project information

site_name: Laboratorio de Amazon Neptune
site_description: 'En este laboratorio usted recorrerá las preferencias de juegos de consola de un conjunto de datos de jugadores y juegos utilizando Amazon Neptune y Gremlin.'
#site_author: 'josepenu@amazon.com'
site_url: 'http://neptune.oldschool.cloud'

# Repository
#repo_name: 'name'
repo_url: 'https://github.com/josemp-git/neptune'

google_analytics: ['UA-177862521-1', 'neptune.oldschool.cloud']

# Copyright
copyright: '&copy; 2020 - José Peñúñuri '

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/josemp-git
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jose_penunuri
    - icon: fontawesome/solid/home
      link: http://neptune.oldschool.cloud

nav:
    - Inicio: index.md
    - 1. Preparación del ambiente: setup.md
    - 2. Cargar datos en Neptune: cargardatos.md
    - 3. Conectar con Neptune: connect.md
    - 4. Consultas con Gremlin: gremlin.md
    - 5. HTTPS REST Endpoint: rest.md
    - 6. Integración con Python: python.md
theme:
  name: material
  palette:
    primary: Green
    accent: orange
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pyembed.markdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg